CREATE TABLE "cpus" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"base_clock" varchar(50),
	"turbo_clock" varchar(50),
	"unlocked_multiplier" boolean,
	"cores" varchar(20),
	"threads" varchar(20),
	"tdp" varchar(50),
	"socket" varchar(50),
	"integrated_gpu" varchar(100),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "gpus" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"length" varchar(50),
	"slots" varchar(20),
	"pin8_connectors" integer,
	"pin6_connectors" integer,
	"hdmi" integer,
	"display_port" integer,
	"dvi" integer,
	"vga" integer,
	"boost_clock" varchar(50),
	"vram" varchar(50),
	"memory_clock" varchar(50),
	"tdp" varchar(50),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "rams" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"ram_type" varchar(50),
	"size" varchar(50),
	"clock" varchar(50),
	"timings" varchar(100),
	"sticks" integer,
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "ssds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"form_factor" varchar(50),
	"protocol" varchar(50),
	"size" varchar(50),
	"nand" varchar(50),
	"controller" varchar(100),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "hdds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"form_factor" varchar(50),
	"size" varchar(50),
	"rpm" varchar(50),
	"cache" varchar(50),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "motherboards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"socket" varchar(50),
	"chipset" varchar(50),
	"unlocked" boolean,
	"form_factor" varchar(50),
	"memory_type" varchar(50),
	"memory_capacity" varchar(50),
	"ram_slots" integer,
	"sata" integer,
	"vga" integer,
	"dvi" integer,
	"display_port" integer,
	"hdmi" integer,
	"wifi" boolean,
	"integrated_graphics" boolean,
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "psus" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"watt" varchar(50),
	"size" varchar(50),
	"efficiency_rating" varchar(50),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "cpu_coolers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"supported_sockets" varchar(512),
	"height" varchar(50),
	"tdp" varchar(50),
	"fans_80mm" integer,
	"fans_92mm" integer,
	"fans_120mm" integer,
	"fans_140mm" integer,
	"fans_200mm" integer,
	"additional_fan_support" boolean,
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "monitors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"resolution" varchar(50),
	"refresh_rate" varchar(50),
	"size" varchar(50),
	"panel" varchar(50),
	"response_time" varchar(50),
	"hdmi" integer,
	"display_port" integer,
	"dvi" integer,
	"vga" integer,
	"speaker" boolean,
	"curved" boolean,
	"adjustable_height" boolean,
	"sync" varchar(50),
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
CREATE TABLE "cases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric NOT NULL,
	"producer" varchar(100),
	"mpn" varchar(100),
	"ean" varchar(50),
	"upc" varchar(50),
	"width" varchar(50),
	"depth" varchar(50),
	"height" varchar(50),
	"motherboard" varchar(50),
	"power_supply" varchar(50),
	"supported_gpu_length" varchar(50),
	"supported_cpu_cooler_height" varchar(50),
	"fans_80mm" varchar(50),
	"fans_120mm" varchar(50),
	"fans_140mm" varchar(50),
	"fans_200mm" varchar(50),
	"radiator_120mm" integer,
	"radiator_140mm" integer,
	"radiator_240mm" integer,
	"radiator_280mm" integer,
	"radiator_360mm" integer,
	"disk_25" integer,
	"disk_35" integer,
	"disk_25_35" integer,
	"disk_525" integer,
	"primary_colors" varchar(100),
	"window" boolean,
	"dust_filter" boolean,
	"cable_management" boolean,
	"noise_isolation" boolean,
	"product_page" varchar(512),
	"image_url" varchar(512),
	"stock" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"category_id" uuid
);
--> statement-breakpoint
DROP TABLE "products" CASCADE;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "role" varchar(20) DEFAULT 'user' NOT NULL;--> statement-breakpoint
ALTER TABLE "cpus" ADD CONSTRAINT "cpus_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gpus" ADD CONSTRAINT "gpus_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rams" ADD CONSTRAINT "rams_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ssds" ADD CONSTRAINT "ssds_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hdds" ADD CONSTRAINT "hdds_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "motherboards" ADD CONSTRAINT "motherboards_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psus" ADD CONSTRAINT "psus_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cpu_coolers" ADD CONSTRAINT "cpu_coolers_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitors" ADD CONSTRAINT "monitors_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;