// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Products.tsx": {
    id: "pages/Products";
    page: "/products";
  };
};