// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/category/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/logowanie": {
    params: {};
  };
  "/rejestracja": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/AdminLogin": {
    params: {};
  };
  "/AdminUsers": {
    params: {};
  };
  "/AdminCategories": {
    params: {};
  };
  "/AdminProducts": {
    params: {};
  };
  "/AdminTags": {
    params: {};
  };
  "/AdminOrders": {
    params: {};
  };
  "/AdminSettings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:slug" | "/category/:id" | "/login" | "/logowanie" | "/rejestracja" | "/cart" | "/AdminLogin" | "/AdminUsers" | "/AdminCategories" | "/AdminProducts" | "/AdminTags" | "/AdminOrders" | "/AdminSettings";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Products.tsx": {
    id: "pages/Products";
    page: "/products";
  };
  "./pages/ProductDetail.tsx": {
    id: "pages/ProductDetail";
    page: "/products/:slug";
  };
  "./pages/Category.tsx": {
    id: "pages/Category";
    page: "/category/:id";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  } | {
    id: "pages/Login-pl";
    page: "/logowanie";
  };
  "./pages/Register.tsx": {
    id: "pages/Register";
    page: "/rejestracja";
  };
  "./pages/Cart.tsx": {
    id: "pages/Cart";
    page: "/cart";
  };
  "./pages/admin/Login.tsx": {
    id: "pages/admin/Login";
    page: "/AdminLogin";
  };
  "./pages/admin/Users.tsx": {
    id: "pages/admin/Users";
    page: "/AdminUsers";
  };
  "./pages/admin/Categories.tsx": {
    id: "pages/admin/Categories";
    page: "/AdminCategories";
  };
  "./pages/admin/Products.tsx": {
    id: "pages/admin/Products";
    page: "/AdminProducts";
  };
  "./pages/admin/Tags.tsx": {
    id: "pages/admin/Tags";
    page: "/AdminTags";
  };
  "./pages/admin/Orders.tsx": {
    id: "pages/admin/Orders";
    page: "/AdminOrders";
  };
  "./pages/admin/Settings.tsx": {
    id: "pages/admin/Settings";
    page: "/AdminSettings";
  };
};