// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/logowanie": {
    params: {};
  };
  "/rejestracja": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:slug" | "/logowanie" | "/rejestracja";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Products.tsx": {
    id: "pages/Products";
    page: "/products";
  };
  "./pages/ProductDetail.tsx": {
    id: "pages/ProductDetail";
    page: "/products/:slug";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/logowanie";
  };
  "./pages/Register.tsx": {
    id: "pages/Register";
    page: "/rejestracja";
  };
};